### ISSUE TITLE
ios 运行失败

### ISSUE THREAD

**Issue by mingmingjiu** [jiasongs/react-native-refresh#1]
"RCTRefreshHeader" was not found in the UiManager。
This error is located at: in RCTRefreshHeader(at RefreshHeader.ios.js)

**Comment by jiasongs** [comment]
使用的是本库哪个版本，RN是哪个版本，如果有需要请我加我QQ：593908937

**Comment by mingmingjiu** [comment]
已经ok了，iOS同事看了下配置好了，组件写的很棒
